import type { InsertMenuItem, InsertReview } from "../../drizzle/schema";

/**
 * Menu items and reviews data for Tokyo Vegan Bites
 */

// Sample user IDs for reviews (in production, these would be real user IDs)
const sampleUserIds = [
  "user-ken-okamoto",
  "user-yuki-tanaka",
  "user-sarah-johnson",
  "user-takeshi-yamada",
  "user-emily-chen",
  "user-hiroshi-sato",
  "user-maria-garcia",
  "user-kenji-nakamura",
];

export const menuItems: Omit<InsertMenuItem, "createdAt">[] = [
  // 8ablish
  {
    id: "menu-8ablish-burger",
    restaurantId: "8ablish-omotesando",
    name: "Organic Vegan Burger",
    nameJa: "オーガニックヴィーガンバーガー",
    description: "Juicy plant-based patty with fresh vegetables and special sauce",
    descriptionJa: "ジューシーな植物性パティと新鮮な野菜、特製ソース",
    price: 1800,
    category: "Main",
    image: "/images/menu/8ablish-burger.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy"]),
  },
  {
    id: "menu-8ablish-fries",
    restaurantId: "8ablish-omotesando",
    name: "Organic French Fries",
    nameJa: "オーガニックフレンチフライ",
    description: "Crispy fries made from organic potatoes",
    descriptionJa: "オーガニックポテトで作ったクリスピーなフライ",
    price: 600,
    category: "Side",
    image: "/images/menu/8ablish-fries.jpg",
    isVegan: true,
    allergens: JSON.stringify([]),
  },
  {
    id: "menu-8ablish-shake",
    restaurantId: "8ablish-omotesando",
    name: "Vegan Milkshake",
    nameJa: "ヴィーガンミルクシェイク",
    description: "Creamy plant-based milkshake in various flavors",
    descriptionJa: "様々なフレーバーのクリーミーな植物性ミルクシェイク",
    price: 800,
    category: "Drink",
    image: "/images/menu/8ablish-shake.jpg",
    isVegan: true,
    allergens: JSON.stringify(["soy"]),
  },

  // T's TanTan
  {
    id: "menu-ts-tantan-ramen",
    restaurantId: "ts-tantan-tokyo-station",
    name: "Vegan Tantan-men",
    nameJa: "ヴィーガン担々麺",
    description: "Spicy sesame-based ramen with plant-based meat",
    descriptionJa: "植物性ミートを使ったスパイシーな胡麻ベースのラーメン",
    price: 1100,
    category: "Main",
    image: "/images/menu/ts-tantan-ramen.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy", "sesame"]),
  },
  {
    id: "menu-ts-tantan-gyoza",
    restaurantId: "ts-tantan-tokyo-station",
    name: "Vegan Gyoza",
    nameJa: "ヴィーガン餃子",
    description: "Pan-fried dumplings with vegetable filling",
    descriptionJa: "野菜餡の焼き餃子",
    price: 500,
    category: "Side",
    image: "/images/menu/ts-tantan-gyoza.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy"]),
  },

  // Ain Soph Journey
  {
    id: "menu-ain-soph-pancakes",
    restaurantId: "ain-soph-journey-shinjuku",
    name: "Fluffy Vegan Pancakes",
    nameJa: "ふわふわヴィーガンパンケーキ",
    description: "Stack of fluffy pancakes with seasonal fruits and maple syrup",
    descriptionJa: "季節のフルーツとメープルシロップのふわふわパンケーキ",
    price: 1600,
    category: "Main",
    image: "/images/menu/ain-soph-pancakes.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy"]),
  },
  {
    id: "menu-ain-soph-burger",
    restaurantId: "ain-soph-journey-shinjuku",
    name: "Avocado Burger",
    nameJa: "アボカドバーガー",
    description: "Plant-based burger with fresh avocado and special sauce",
    descriptionJa: "新鮮なアボカドと特製ソースの植物性バーガー",
    price: 1800,
    category: "Main",
    image: "/images/menu/ain-soph-burger.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy"]),
  },
  {
    id: "menu-ain-soph-cake",
    restaurantId: "ain-soph-journey-shinjuku",
    name: "Vegan Chocolate Cake",
    nameJa: "ヴィーガンチョコレートケーキ",
    description: "Rich chocolate cake made without eggs or dairy",
    descriptionJa: "卵・乳製品不使用の濃厚チョコレートケーキ",
    price: 900,
    category: "Dessert",
    image: "/images/menu/ain-soph-cake.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy"]),
  },

  // Nataraj Shibuya
  {
    id: "menu-nataraj-curry-set",
    restaurantId: "nataraj-shibuya",
    name: "Curry Set",
    nameJa: "カレーセット",
    description: "Choose 2 curries from 20+ varieties with rice and naan",
    descriptionJa: "20種類以上から2種類のカレーを選べるセット（ライス・ナン付き）",
    price: 1400,
    category: "Main",
    image: "/images/menu/nataraj-curry.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten"]),
  },
  {
    id: "menu-nataraj-samosa",
    restaurantId: "nataraj-shibuya",
    name: "Vegetable Samosa",
    nameJa: "野菜サモサ",
    description: "Crispy fried pastry filled with spiced vegetables",
    descriptionJa: "スパイスの効いた野菜入りのサクサクした揚げパン",
    price: 600,
    category: "Side",
    image: "/images/menu/nataraj-samosa.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten"]),
  },

  // Loving Hut
  {
    id: "menu-loving-hut-mapo",
    restaurantId: "loving-hut-ikebukuro",
    name: "Vegan Mapo Tofu",
    nameJa: "ヴィーガン麻婆豆腐",
    description: "Spicy tofu dish with plant-based meat",
    descriptionJa: "植物性ミートを使ったスパイシーな豆腐料理",
    price: 950,
    category: "Main",
    image: "/images/menu/loving-hut-mapo.jpg",
    isVegan: true,
    allergens: JSON.stringify(["soy"]),
  },
  {
    id: "menu-loving-hut-noodles",
    restaurantId: "loving-hut-ikebukuro",
    name: "Dan Dan Noodles",
    nameJa: "担々麺",
    description: "Spicy sesame noodles with vegetables",
    descriptionJa: "野菜入りのスパイシーな胡麻麺",
    price: 1000,
    category: "Main",
    image: "/images/menu/loving-hut-noodles.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy", "sesame"]),
  },

  // Nagi Shokudo
  {
    id: "menu-nagi-teishoku",
    restaurantId: "nagi-shokudo-shibuya",
    name: "Macrobiotic Set Meal",
    nameJa: "マクロビオティック定食",
    description: "Traditional Japanese set meal with brown rice and seasonal vegetables",
    descriptionJa: "玄米と季節の野菜を使った伝統的な和定食",
    price: 1500,
    category: "Main",
    image: "/images/menu/nagi-teishoku.jpg",
    isVegan: true,
    allergens: JSON.stringify(["soy"]),
  },
  {
    id: "menu-nagi-miso-soup",
    restaurantId: "nagi-shokudo-shibuya",
    name: "Organic Miso Soup",
    nameJa: "オーガニック味噌汁",
    description: "Traditional miso soup with organic ingredients",
    descriptionJa: "オーガニック食材を使った伝統的な味噌汁",
    price: 400,
    category: "Side",
    image: "/images/menu/nagi-miso.jpg",
    isVegan: true,
    allergens: JSON.stringify(["soy"]),
  },

  // Saido
  {
    id: "menu-saido-course",
    restaurantId: "saido-roppongi",
    name: "Seasonal Vegetable Course",
    nameJa: "季節の野菜コース",
    description: "Multi-course meal featuring seasonal organic vegetables",
    descriptionJa: "季節のオーガニック野菜を使ったコース料理",
    price: 5500,
    category: "Main",
    image: "/images/menu/saido-course.jpg",
    isVegan: true,
    allergens: JSON.stringify(["soy"]),
  },

  // Vegan Ramen UZU
  {
    id: "menu-uzu-shoyu",
    restaurantId: "vegan-ramen-uzu-kyoto",
    name: "Vegan Shoyu Ramen",
    nameJa: "ヴィーガン醤油ラーメン",
    description: "Classic soy sauce ramen with rich vegetable broth",
    descriptionJa: "濃厚な野菜出汁の醤油ラーメン",
    price: 1200,
    category: "Main",
    image: "/images/menu/uzu-shoyu.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy"]),
  },
  {
    id: "menu-uzu-miso",
    restaurantId: "vegan-ramen-uzu-kyoto",
    name: "Vegan Miso Ramen",
    nameJa: "ヴィーガン味噌ラーメン",
    description: "Rich miso ramen with seasonal vegetables",
    descriptionJa: "季節の野菜入りの濃厚味噌ラーメン",
    price: 1300,
    category: "Main",
    image: "/images/menu/uzu-miso.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy"]),
  },

  // Soranoiro
  {
    id: "menu-soranoiro-veggie-tantan",
    restaurantId: "soranoiro-vegan",
    name: "Veggie Tantanmen",
    nameJa: "ベジ担々麺",
    description: "Award-winning veggie-based tantanmen with rich sesame broth",
    descriptionJa: "受賞歴のある野菜ベースの担々麺、濃厚胡麻スープ",
    price: 1400,
    category: "Main",
    image: "/images/menu/soranoiro-tantan.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy", "sesame"]),
  },

  // AFURI
  {
    id: "menu-afuri-yuzu-shio",
    restaurantId: "afuri-vegan-ramen",
    name: "Vegan Yuzu Shio Ramen",
    nameJa: "ヴィーガン柚子塩ラーメン",
    description: "Light and refreshing ramen with yuzu citrus flavor",
    descriptionJa: "柚子の香りが爽やかな軽いラーメン",
    price: 1300,
    category: "Main",
    image: "/images/menu/afuri-yuzu.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy"]),
  },

  // ovgo Baker
  {
    id: "menu-ovgo-cookies",
    restaurantId: "ovgo-baker-shibuya",
    name: "Vegan Cookies (3 pieces)",
    nameJa: "ヴィーガンクッキー（3個）",
    description: "Assorted vegan cookies - chocolate chip, oatmeal, peanut butter",
    descriptionJa: "チョコチップ、オートミール、ピーナッツバターの詰め合わせ",
    price: 800,
    category: "Dessert",
    image: "/images/menu/ovgo-cookies.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy", "nuts"]),
  },
  {
    id: "menu-ovgo-brownie",
    restaurantId: "ovgo-baker-shibuya",
    name: "Vegan Brownie",
    nameJa: "ヴィーガンブラウニー",
    description: "Rich and fudgy chocolate brownie",
    descriptionJa: "濃厚でしっとりしたチョコレートブラウニー",
    price: 500,
    category: "Dessert",
    image: "/images/menu/ovgo-brownie.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy"]),
  },

  // Alaska Zwei
  {
    id: "menu-alaska-brown-rice-plate",
    restaurantId: "alaska-zwei",
    name: "Brown Rice Plate",
    nameJa: "玄米ごはんプレート",
    description: "Organic brown rice with various vegetable side dishes",
    descriptionJa: "オーガニック玄米と様々な野菜のおかず",
    price: 1600,
    category: "Main",
    image: "/images/menu/alaska-plate.jpg",
    isVegan: true,
    allergens: JSON.stringify(["soy"]),
  },

  // Bon
  {
    id: "menu-bon-fuscha-course",
    restaurantId: "bon-iriya",
    name: "Fuscha Ryori Course",
    nameJa: "普茶料理コース",
    description: "Traditional Buddhist vegetarian course meal",
    descriptionJa: "伝統的な仏教精進料理のコース",
    price: 8000,
    category: "Main",
    image: "/images/menu/bon-course.jpg",
    isVegan: true,
    allergens: JSON.stringify(["soy", "gluten"]),
  },

  // 2foods
  {
    id: "menu-2foods-burger",
    restaurantId: "2foods-ginza-loft",
    name: "Plant-Based Burger",
    nameJa: "プラントベースバーガー",
    description: "Juicy plant-based burger with fries",
    descriptionJa: "ジューシーな植物性バーガーとフライ",
    price: 1700,
    category: "Main",
    image: "/images/menu/2foods-burger.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy"]),
  },
  {
    id: "menu-2foods-donuts",
    restaurantId: "2foods-ginza-loft",
    name: "Vegan Donuts (2 pieces)",
    nameJa: "ヴィーガンドーナツ（2個）",
    description: "Soft and sweet vegan donuts",
    descriptionJa: "ふわふわで甘いヴィーガンドーナツ",
    price: 600,
    category: "Dessert",
    image: "/images/menu/2foods-donuts.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy"]),
  },

  // Thai Vegan
  {
    id: "menu-thai-pad-thai",
    restaurantId: "thai-vegan-yoyogi",
    name: "Vegan Pad Thai",
    nameJa: "ヴィーガンパッタイ",
    description: "Classic Thai stir-fried noodles with tofu and vegetables",
    descriptionJa: "豆腐と野菜の伝統的なタイ風焼きそば",
    price: 1300,
    category: "Main",
    image: "/images/menu/thai-pad-thai.jpg",
    isVegan: true,
    allergens: JSON.stringify(["gluten", "soy", "nuts"]),
  },
  {
    id: "menu-thai-green-curry",
    restaurantId: "thai-vegan-yoyogi",
    name: "Vegan Green Curry",
    nameJa: "ヴィーガングリーンカレー",
    description: "Spicy green curry with vegetables and tofu",
    descriptionJa: "野菜と豆腐のスパイシーなグリーンカレー",
    price: 1400,
    category: "Main",
    image: "/images/menu/thai-green-curry.jpg",
    isVegan: true,
    allergens: JSON.stringify(["soy"]),
  },

  // .RAW
  {
    id: "menu-raw-salad-bar",
    restaurantId: "dot-raw-roppongi",
    name: "Organic Salad Bar",
    nameJa: "オーガニックサラダバー",
    description: "All-you-can-eat salad bar with homegrown sprouts",
    descriptionJa: "自家栽培スプラウト入りのサラダバー食べ放題",
    price: 1800,
    category: "Main",
    image: "/images/menu/raw-salad.jpg",
    isVegan: true,
    allergens: JSON.stringify([]),
  },
  {
    id: "menu-raw-dessert",
    restaurantId: "dot-raw-roppongi",
    name: "Raw Vegan Dessert",
    nameJa: "ローヴィーガンデザート",
    description: "Raw vegan dessert made without cooking",
    descriptionJa: "加熱せずに作ったローヴィーガンデザート",
    price: 900,
    category: "Dessert",
    image: "/images/menu/raw-dessert.jpg",
    isVegan: true,
    allergens: JSON.stringify(["nuts"]),
  },
];

export const reviews: Omit<InsertReview, "createdAt">[] = [
  // 8ablish reviews
  {
    id: "review-8ablish-1",
    userId: sampleUserIds[0],
    restaurantId: "8ablish-omotesando",
    rating: 5,
    comment: "Amazing vegan burger! The patty was juicy and flavorful. The atmosphere is great too. Highly recommended!",
  },
  {
    id: "review-8ablish-2",
    userId: sampleUserIds[1],
    restaurantId: "8ablish-omotesando",
    rating: 5,
    comment: "表参道で最高のヴィーガンバーガー！パティがジューシーで本当に美味しい。クラフトビールも豊富です。",
  },
  {
    id: "review-8ablish-3",
    userId: sampleUserIds[2],
    restaurantId: "8ablish-omotesando",
    rating: 4,
    comment: "Great burger but a bit pricey. The quality is excellent though. Will definitely come back!",
  },
  {
    id: "review-8ablish-4",
    userId: sampleUserIds[3],
    restaurantId: "8ablish-omotesando",
    rating: 5,
    comment: "ヴィーガンとは思えないクオリティ！フレンチフライも最高に美味しかったです。",
  },

  // T's TanTan reviews
  {
    id: "review-ts-tantan-1",
    userId: sampleUserIds[4],
    restaurantId: "ts-tantan-tokyo-station",
    rating: 5,
    comment: "Perfect for a quick meal at Tokyo Station! The tantan-men is delicious and affordable.",
  },
  {
    id: "review-ts-tantan-2",
    userId: sampleUserIds[5],
    restaurantId: "ts-tantan-tokyo-station",
    rating: 4,
    comment: "東京駅で手軽にヴィーガンラーメンが食べられるのは嬉しい。担々麺が特におすすめ！",
  },
  {
    id: "review-ts-tantan-3",
    userId: sampleUserIds[6],
    restaurantId: "ts-tantan-tokyo-station",
    rating: 5,
    comment: "Best vegan ramen I've had in Tokyo! The sesame broth is rich and flavorful.",
  },

  // Ain Soph Journey reviews
  {
    id: "review-ain-soph-1",
    userId: sampleUserIds[0],
    restaurantId: "ain-soph-journey-shinjuku",
    rating: 5,
    comment: "The pancakes are absolutely amazing! So fluffy and delicious. The cafe has a great atmosphere.",
  },
  {
    id: "review-ain-soph-2",
    userId: sampleUserIds[1],
    restaurantId: "ain-soph-journey-shinjuku",
    rating: 5,
    comment: "パンケーキが本当にふわふわで美味しい！インスタ映えもするし、味も最高です。",
  },
  {
    id: "review-ain-soph-3",
    userId: sampleUserIds[2],
    restaurantId: "ain-soph-journey-shinjuku",
    rating: 4,
    comment: "Great vegan cafe with creative menu. The burger was delicious. A bit crowded on weekends.",
  },
  {
    id: "review-ain-soph-4",
    userId: sampleUserIds[7],
    restaurantId: "ain-soph-journey-shinjuku",
    rating: 5,
    comment: "新宿でヴィーガン料理を楽しむならここ！デザートも充実していて大満足でした。",
  },

  // Nataraj Shibuya reviews
  {
    id: "review-nataraj-1",
    userId: sampleUserIds[3],
    restaurantId: "nataraj-shibuya",
    rating: 5,
    comment: "Authentic Indian vegetarian cuisine! Over 20 curry options to choose from. Everything is delicious!",
  },
  {
    id: "review-nataraj-2",
    userId: sampleUserIds[4],
    restaurantId: "nataraj-shibuya",
    rating: 5,
    comment: "日本初のベジタリアンインド料理店。カレーの種類が豊富で、どれも本格的な味わいです。",
  },
  {
    id: "review-nataraj-3",
    userId: sampleUserIds[5],
    restaurantId: "nataraj-shibuya",
    rating: 4,
    comment: "Great curry selection and the naan is amazing. Organic vegetables make it even better!",
  },

  // Loving Hut reviews
  {
    id: "review-loving-hut-1",
    userId: sampleUserIds[6],
    restaurantId: "loving-hut-ikebukuro",
    rating: 4,
    comment: "Affordable vegan Chinese food! The mapo tofu is my favorite. Great for quick lunch.",
  },
  {
    id: "review-loving-hut-2",
    userId: sampleUserIds[7],
    restaurantId: "loving-hut-ikebukuro",
    rating: 4,
    comment: "池袋で手頃な価格のヴィーガン中華。麻婆豆腐が特に美味しかったです。",
  },
  {
    id: "review-loving-hut-3",
    userId: sampleUserIds[0],
    restaurantId: "loving-hut-ikebukuro",
    rating: 5,
    comment: "International chain but quality is consistent. Love their dan dan noodles!",
  },

  // Nagi Shokudo reviews
  {
    id: "review-nagi-1",
    userId: sampleUserIds[1],
    restaurantId: "nagi-shokudo-shibuya",
    rating: 5,
    comment: "Beautiful macrobiotic set meals with organic ingredients. Healthy and delicious!",
  },
  {
    id: "review-nagi-2",
    userId: sampleUserIds[2],
    restaurantId: "nagi-shokudo-shibuya",
    rating: 5,
    comment: "渋谷でマクロビオティック料理が食べられる貴重なお店。玄米定食が絶品です。",
  },
  {
    id: "review-nagi-3",
    userId: sampleUserIds[3],
    restaurantId: "nagi-shokudo-shibuya",
    rating: 4,
    comment: "Traditional Japanese vegan food done right. The brown rice is perfectly cooked.",
  },

  // Saido reviews
  {
    id: "review-saido-1",
    userId: sampleUserIds[4],
    restaurantId: "saido-roppongi",
    rating: 5,
    comment: "Upscale organic Japanese restaurant. The seasonal vegetable course is outstanding!",
  },
  {
    id: "review-saido-2",
    userId: sampleUserIds[5],
    restaurantId: "saido-roppongi",
    rating: 5,
    comment: "六本木の高級オーガニック和食。旬の野菜を使ったコース料理が素晴らしい。特別な日におすすめ。",
  },
  {
    id: "review-saido-3",
    userId: sampleUserIds[6],
    restaurantId: "saido-roppongi",
    rating: 4,
    comment: "Beautiful presentation and delicious food. Perfect for business dinners or special occasions.",
  },

  // Vegan Ramen UZU reviews
  {
    id: "review-uzu-1",
    userId: sampleUserIds[7],
    restaurantId: "vegan-ramen-uzu-kyoto",
    rating: 5,
    comment: "Authentic vegan ramen with rich broth! Multiple soup options available. Highly recommended!",
  },
  {
    id: "review-uzu-2",
    userId: sampleUserIds[0],
    restaurantId: "vegan-ramen-uzu-kyoto",
    rating: 5,
    comment: "新宿で本格的なヴィーガンラーメン。スープが濃厚で美味しい！グルテンフリーオプションもあります。",
  },
  {
    id: "review-uzu-3",
    userId: sampleUserIds[1],
    restaurantId: "vegan-ramen-uzu-kyoto",
    rating: 4,
    comment: "Great ramen with flavorful broth. The toppings are fresh and generous.",
  },

  // Soranoiro reviews
  {
    id: "review-soranoiro-1",
    userId: sampleUserIds[2],
    restaurantId: "soranoiro-vegan",
    rating: 5,
    comment: "Award-winning vegan ramen! The veggie tantanmen is incredible. Must try!",
  },
  {
    id: "review-soranoiro-2",
    userId: sampleUserIds[3],
    restaurantId: "soranoiro-vegan",
    rating: 5,
    comment: "受賞歴のあるヴィーガンラーメン店。野菜ベースの担々麺が絶品です。",
  },

  // AFURI reviews
  {
    id: "review-afuri-1",
    userId: sampleUserIds[4],
    restaurantId: "afuri-vegan-ramen",
    rating: 4,
    comment: "Light and refreshing yuzu ramen. Perfect for summer! Modern interior is nice too.",
  },
  {
    id: "review-afuri-2",
    userId: sampleUserIds[5],
    restaurantId: "afuri-vegan-ramen",
    rating: 4,
    comment: "原宿で柚子塩ラーメン。爽やかな味わいで美味しい。ヴィーガンオプションがあるのが嬉しい。",
  },

  // ovgo Baker reviews
  {
    id: "review-ovgo-1",
    userId: sampleUserIds[6],
    restaurantId: "ovgo-baker-shibuya",
    rating: 5,
    comment: "Best vegan cookies and brownies in Tokyo! Everything is delicious and affordable.",
  },
  {
    id: "review-ovgo-2",
    userId: sampleUserIds[7],
    restaurantId: "ovgo-baker-shibuya",
    rating: 5,
    comment: "渋谷で手軽に買えるヴィーガンスイーツ。クッキーもブラウニーも最高に美味しい！",
  },

  // Alaska Zwei reviews
  {
    id: "review-alaska-1",
    userId: sampleUserIds[0],
    restaurantId: "alaska-zwei",
    rating: 5,
    comment: "Cozy vegan cafe with naturally cultivated vegetables. The brown rice plate is my favorite!",
  },
  {
    id: "review-alaska-2",
    userId: sampleUserIds[1],
    restaurantId: "alaska-zwei",
    rating: 5,
    comment: "中目黒の隠れ家的ヴィーガンカフェ。自然栽培野菜を使った玄米プレートが絶品です。",
  },

  // Bon reviews
  {
    id: "review-bon-1",
    userId: sampleUserIds[2],
    restaurantId: "bon-iriya",
    rating: 5,
    comment: "Traditional fuscha ryori in a beautiful setting. The course meal is exquisite. Reservation required.",
  },
  {
    id: "review-bon-2",
    userId: sampleUserIds[3],
    restaurantId: "bon-iriya",
    rating: 5,
    comment: "昭和34年創業の伝統的な普茶料理。全席個室で特別な日にぴったり。コース料理が素晴らしい。",
  },

  // 2foods reviews
  {
    id: "review-2foods-1",
    userId: sampleUserIds[4],
    restaurantId: "2foods-ginza-loft",
    rating: 4,
    comment: "Convenient vegan fast food in Ginza Loft. The burger and donuts are great!",
  },
  {
    id: "review-2foods-2",
    userId: sampleUserIds[5],
    restaurantId: "2foods-ginza-loft",
    rating: 4,
    comment: "銀座ロフトで手軽にヴィーガンファストフード。バーガーもドーナツも美味しい。",
  },

  // Thai Vegan reviews
  {
    id: "review-thai-1",
    userId: sampleUserIds[6],
    restaurantId: "thai-vegan-yoyogi",
    rating: 5,
    comment: "Authentic Thai vegan food! The pad thai and green curry are amazing. Spice levels are perfect.",
  },
  {
    id: "review-thai-2",
    userId: sampleUserIds[7],
    restaurantId: "thai-vegan-yoyogi",
    rating: 5,
    comment: "代々木で本格的なヴィーガンタイ料理。パッタイもグリーンカレーも本当に美味しい！",
  },

  // .RAW reviews
  {
    id: "review-raw-1",
    userId: sampleUserIds[0],
    restaurantId: "dot-raw-roppongi",
    rating: 4,
    comment: "Unique raw food cafe with salad bar. The homegrown sprouts are super fresh!",
  },
  {
    id: "review-raw-2",
    userId: sampleUserIds[1],
    restaurantId: "dot-raw-roppongi",
    rating: 4,
    comment: "六本木のローフードカフェ。自家栽培スプラウトのサラダバーが新鮮で美味しい。",
  },
];

