import type { InsertRestaurant } from "../../drizzle/schema";

/**
 * Extended restaurant data for Tokyo Vegan Bites
 * Total: 50+ restaurants across Tokyo
 */
export const extendedRestaurants: Omit<InsertRestaurant, "createdAt" | "updatedAt">[] = [
  // Category 1: 100% Vegan Restaurants
  
  // Ramen Restaurants
  {
    id: "ts-tantan-tokyo-station",
    name: "T's TanTan Tokyo Station",
    nameJa: "T's たんたん 東京駅店",
    address: "1-9-1 Marunouchi, Chiyoda-ku, Tokyo Station, Keiyo Street",
    lat: "35.6812",
    lng: "139.7671",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Ramen", "Japanese"]),
    priceRange: "¥",
    features: JSON.stringify(["Quick Service", "Station Location"]),
    instagram: "@tstantan_official",
    website: "https://ts-restaurant.jp/",
    phone: "03-3218-8040",
    hours: "8:00-22:00 (Mon-Sat), 8:00-21:00 (Sun)",
    description: "Vegan ramen restaurant located inside Tokyo Station. Famous for their tantan-men (sesame paste noodles) made entirely plant-based.",
    descriptionJa: "東京駅構内にあるヴィーガンラーメン店。完全植物性の担々麺が有名です。",
    heroImage: "/images/restaurants/ts-tantan.jpg",
  },
  {
    id: "vegan-ramen-uzu-kyoto",
    name: "Vegan Ramen UZU Kyoto",
    nameJa: "ヴィーガンラーメン宇豆 京都",
    address: "3-14-1 Nishishinjuku, Shinjuku-ku, Tokyo",
    lat: "35.6896",
    lng: "139.6917",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Ramen", "Japanese"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Organic", "Gluten-Free Options"]),
    instagram: "@veganramenuzu",
    website: "https://vegan-uzu.com/",
    phone: "03-5358-9022",
    hours: "11:30-15:00, 18:00-22:00 (Closed Wed)",
    description: "Authentic vegan ramen with rich, flavorful broth made from vegetables and kombu. Multiple soup options available.",
    descriptionJa: "野菜と昆布から作られた濃厚で風味豊かなスープの本格ヴィーガンラーメン。複数のスープオプションあり。",
    heroImage: "/images/restaurants/vegan-ramen-uzu.jpg",
  },
  {
    id: "soranoiro-vegan",
    name: "Soranoiro Vegan Style",
    nameJa: "ソラノイロ ヴィーガンスタイル",
    address: "1-2-3 Kojimachi, Chiyoda-ku, Tokyo",
    lat: "35.6850",
    lng: "139.7450",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Ramen", "Japanese"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Award-Winning", "Creative Menu"]),
    instagram: "@soranoiro_vegan",
    website: "https://soranoiro-vege.com/",
    phone: "03-3265-5460",
    hours: "11:00-15:00, 17:00-21:00 (Closed Sun)",
    description: "Award-winning vegan ramen shop with creative plant-based broths. Known for their veggie-based tantanmen.",
    descriptionJa: "受賞歴のあるヴィーガンラーメン店。創造的な植物ベースのスープが特徴。野菜ベースの担々麺が有名。",
    heroImage: "/images/restaurants/soranoiro.jpg",
  },
  {
    id: "afuri-vegan-ramen",
    name: "AFURI Vegan Ramen",
    nameJa: "阿夫利 ヴィーガンラーメン",
    address: "1-1-7 Jingumae, Shibuya-ku, Harajuku, Tokyo",
    lat: "35.6702",
    lng: "139.7026",
    veganLevel: "Vegan Options",
    cuisineTypes: JSON.stringify(["Ramen", "Japanese"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Yuzu Flavor", "Modern Interior"]),
    instagram: "@afuri_ramen",
    website: "https://afuri.com/",
    phone: "03-6447-1910",
    hours: "11:00-23:00 (Daily)",
    description: "Popular ramen chain offering vegan yuzu shio ramen. Light, refreshing broth with citrus notes.",
    descriptionJa: "ヴィーガン柚子塩ラーメンを提供する人気ラーメンチェーン。柑橘の香りが爽やかな軽いスープ。",
    heroImage: "/images/restaurants/afuri.jpg",
  },

  // Burger Restaurants
  {
    id: "8ablish-omotesando",
    name: "8ablish",
    nameJa: "エイタブリッシュ",
    address: "5-51-8 Jingumae, Shibuya-ku, Omotesando, Tokyo",
    lat: "35.6652",
    lng: "139.7100",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Burger", "American"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Plant-Based Meat", "Craft Beer"]),
    instagram: "@8ablish_tokyo",
    website: "https://8ablish.com/",
    phone: "03-6427-4207",
    hours: "11:30-22:00 (Daily)",
    description: "100% plant-based burger joint in Omotesando. Juicy burgers made with premium plant-based meat.",
    descriptionJa: "表参道にある100%プラントベースのバーガーショップ。プレミアムな植物性ミートを使用したジューシーなバーガー。",
    heroImage: "/images/restaurants/8ablish.jpg",
  },
  {
    id: "great-lakes-shibuya",
    name: "Great Lakes Shibuya",
    nameJa: "グレートレイクス 渋谷",
    address: "1-10-2 Jinnan, Shibuya-ku, Tokyo",
    lat: "35.6627",
    lng: "139.6980",
    veganLevel: "Vegan Options",
    cuisineTypes: JSON.stringify(["Burger", "American"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Craft Beer", "Casual Dining"]),
    instagram: "@greatlakes_tokyo",
    website: "https://greatlakes.jp/",
    phone: "03-6416-5477",
    hours: "11:30-23:00 (Daily)",
    description: "American-style burger restaurant with vegan options. Known for their Beyond Burger and craft beer selection.",
    descriptionJa: "ヴィーガンオプションのあるアメリカンスタイルのバーガーレストラン。ビヨンドバーガーとクラフトビールが人気。",
    heroImage: "/images/restaurants/great-lakes.jpg",
  },
  {
    id: "moku-tanaka",
    name: "MOKU Tanaka",
    nameJa: "モク 田中",
    address: "3-15-5 Minami-Otsuka, Toshima-ku, Tokyo",
    lat: "35.7314",
    lng: "139.7282",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Burger", "Cafe"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Organic", "Cozy Atmosphere"]),
    instagram: "@moku_tanaka",
    website: "https://moku-tanaka.com/",
    phone: "03-5980-9341",
    hours: "11:00-20:00 (Closed Mon)",
    description: "Cozy vegan cafe serving organic burgers and comfort food. All ingredients are carefully selected.",
    descriptionJa: "オーガニックバーガーとコンフォートフードを提供する居心地の良いヴィーガンカフェ。全ての食材を厳選。",
    heroImage: "/images/restaurants/moku.jpg",
  },

  // Cafe & Bakery
  {
    id: "ain-soph-journey-shinjuku",
    name: "Ain Soph. Journey",
    nameJa: "アインソフ ジャーニー",
    address: "3-8-9 Shinjuku, Shinjuku-ku, Tokyo",
    lat: "35.6920",
    lng: "139.7050",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Cafe", "Western"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Pancakes", "Desserts", "Instagrammable"]),
    instagram: "@ainsoph.journey",
    website: "https://ain-soph.jp/",
    phone: "03-5361-7840",
    hours: "11:00-21:00 (Daily)",
    description: "Popular vegan cafe famous for fluffy pancakes and creative plant-based dishes. Multiple locations in Tokyo.",
    descriptionJa: "ふわふわのパンケーキと創造的な植物ベースの料理で有名な人気ヴィーガンカフェ。都内に複数店舗。",
    heroImage: "/images/restaurants/ain-soph-journey.jpg",
  },
  {
    id: "ain-soph-ginza",
    name: "Ain Soph. Ginza",
    nameJa: "アインソフ 銀座",
    address: "4-12-1 Ginza, Chuo-ku, Tokyo",
    lat: "35.6711",
    lng: "139.7640",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Cafe", "Western"]),
    priceRange: "¥¥¥",
    features: JSON.stringify(["Fine Dining", "Course Menu", "Elegant"]),
    instagram: "@ainsoph.ginza",
    website: "https://ain-soph.jp/",
    phone: "03-6228-4241",
    hours: "11:30-15:00, 17:30-22:00 (Closed Mon)",
    description: "Upscale vegan restaurant in Ginza offering course menus and refined plant-based cuisine.",
    descriptionJa: "銀座にある高級ヴィーガンレストラン。コースメニューと洗練された植物ベースの料理を提供。",
    heroImage: "/images/restaurants/ain-soph-ginza.jpg",
  },
  {
    id: "ovgo-baker-shibuya",
    name: "ovgo Baker Shibuya",
    nameJa: "オブゴベーカー 渋谷",
    address: "1-11-1 Jinnan, Shibuya-ku, Tokyo",
    lat: "35.6625",
    lng: "139.6982",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Bakery", "Cafe", "Dessert"]),
    priceRange: "¥",
    features: JSON.stringify(["Cookies", "Brownies", "Takeout"]),
    instagram: "@ovgobaker_japan",
    website: "https://ovgobaker.jp/",
    phone: "03-6455-0835",
    hours: "10:00-20:00 (Daily)",
    description: "Vegan bakery specializing in cookies, brownies, and baked goods. All products are egg and dairy-free.",
    descriptionJa: "クッキー、ブラウニー、焼き菓子専門のヴィーガンベーカリー。全商品が卵・乳製品不使用。",
    heroImage: "/images/restaurants/ovgo-baker.jpg",
  },
  {
    id: "universal-bakes-nicome",
    name: "Universal Bakes and Cafe",
    nameJa: "ユニバーサルベイクスアンドカフェ",
    address: "1-14-11 Tomigaya, Shibuya-ku, Tokyo",
    lat: "35.6695",
    lng: "139.6850",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Bakery", "Cafe"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Organic", "Gluten-Free Options", "Sourdough"]),
    instagram: "@universalbakes",
    website: "https://universalbakes.com/",
    phone: "03-6407-0112",
    hours: "8:00-18:00 (Closed Mon)",
    description: "Artisan vegan bakery with organic ingredients. Famous for their sourdough bread and pastries.",
    descriptionJa: "オーガニック食材を使用した職人技のヴィーガンベーカリー。サワードウブレッドとペストリーが有名。",
    heroImage: "/images/restaurants/universal-bakes.jpg",
  },
  {
    id: "alaska-zwei",
    name: "Alaska Zwei",
    nameJa: "アラスカツヴァイ",
    address: "2-14-15 Aobadai, Meguro-ku, Tokyo",
    lat: "35.6530",
    lng: "139.6850",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Cafe", "Organic"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Natural Cultivation", "Brown Rice", "Cozy"]),
    instagram: "@alaskazwei",
    website: "https://alaskazwei.com/",
    phone: "03-6452-3663",
    hours: "11:30-20:00 (Closed Tue)",
    description: "Vegan cafe using naturally cultivated vegetables. Popular for their brown rice plate with various side dishes.",
    descriptionJa: "自然栽培野菜を使用したヴィーガンカフェ。玄米プレートと多彩なおかずが人気。",
    heroImage: "/images/restaurants/alaska-zwei.jpg",
  },

  // Indian Restaurants
  {
    id: "nataraj-shibuya",
    name: "Nataraj Shibuya",
    nameJa: "ナタラジ 渋谷",
    address: "2-10-2 Dogenzaka, Shibuya-ku, Tokyo",
    lat: "35.6590",
    lng: "139.6980",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Indian", "Curry"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Organic", "20+ Curry Types", "Buffet"]),
    instagram: "@nataraj_tokyo",
    website: "https://nataraj.co.jp/",
    phone: "03-5428-5858",
    hours: "11:00-22:00 (Daily)",
    description: "Japan's first vegetarian Indian restaurant, established in 1989. Over 20 types of vegan curry available.",
    descriptionJa: "1989年創業、日本初のベジタリアンインド料理店。20種類以上のヴィーガンカレーを提供。",
    heroImage: "/images/restaurants/nataraj.jpg",
  },
  {
    id: "nataraj-harajuku",
    name: "Nataraj Harajuku",
    nameJa: "ナタラジ 原宿",
    address: "3-20-2 Jingumae, Shibuya-ku, Tokyo",
    lat: "35.6710",
    lng: "139.7070",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Indian", "Curry"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Organic", "Takeout", "Lunch Sets"]),
    instagram: "@nataraj_tokyo",
    website: "https://nataraj.co.jp/",
    phone: "03-5474-0510",
    hours: "11:00-22:00 (Daily)",
    description: "Harajuku branch of the famous vegan Indian restaurant chain. Convenient location near Meiji Shrine.",
    descriptionJa: "有名なヴィーガンインド料理チェーンの原宿店。明治神宮近くの便利な立地。",
    heroImage: "/images/restaurants/nataraj-harajuku.jpg",
  },
  {
    id: "saravanaa-bhavan",
    name: "Saravanaa Bhavan Tokyo",
    nameJa: "サラヴァナバヴァン 東京",
    address: "1-21-15 Nishi-Ikebukuro, Toshima-ku, Tokyo",
    lat: "35.7295",
    lng: "139.7070",
    veganLevel: "Vegan Options",
    cuisineTypes: JSON.stringify(["Indian", "South Indian"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Dosa", "Thali", "Authentic"]),
    instagram: "@saravanaabhavan_tokyo",
    website: "https://www.saravanabhavan.com/",
    phone: "03-5391-7217",
    hours: "11:00-22:00 (Daily)",
    description: "Authentic South Indian restaurant with extensive vegan options. Famous for dosa and thali sets.",
    descriptionJa: "豊富なヴィーガンオプションのある本格南インド料理店。ドーサとターリーセットが有名。",
    heroImage: "/images/restaurants/saravanaa-bhavan.jpg",
  },
  {
    id: "hoba-curry",
    name: "Curry Restaurant HOBA",
    nameJa: "カレーレストラン HOBA",
    address: "2-5-3 Kichijoji Honcho, Musashino-shi, Tokyo",
    lat: "35.7034",
    lng: "139.5800",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Curry", "Japanese"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Homemade", "Spice Blend", "Cozy"]),
    instagram: "@hoba_curry",
    website: "https://hobacurry.com/",
    phone: "0422-27-5262",
    hours: "11:00-18:00 (Closed Thu)",
    description: "Vegan curry restaurant in Kichijoji with homemade spice blends. Cozy atmosphere and friendly service.",
    descriptionJa: "吉祥寺にある自家製スパイスブレンドのヴィーガンカレー店。居心地の良い雰囲気とフレンドリーなサービス。",
    heroImage: "/images/restaurants/hoba.jpg",
  },

  // Japanese Restaurants
  {
    id: "nagi-shokudo-shibuya",
    name: "Nagi Shokudo",
    nameJa: "なぎ食堂",
    address: "1-15-3 Shibuya, Shibuya-ku, Tokyo",
    lat: "35.6595",
    lng: "139.7020",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Japanese", "Macrobiotic"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Organic", "Macrobiotic", "Set Meals"]),
    instagram: "@nagi_shokudo",
    website: "https://nagi-shokudo.jp/",
    phone: "03-5468-3368",
    hours: "11:30-15:00, 18:00-22:00 (Closed Sun)",
    description: "Macrobiotic vegan restaurant offering traditional Japanese set meals with organic ingredients.",
    descriptionJa: "オーガニック食材を使用した伝統的な和定食を提供するマクロビオティックヴィーガンレストラン。",
    heroImage: "/images/restaurants/nagi-shokudo.jpg",
  },
  {
    id: "bon-iriya",
    name: "Fuscha Ryori Bon",
    nameJa: "普茶料理 梵",
    address: "1-2-11 Shitaya, Taito-ku, Tokyo",
    lat: "35.7210",
    lng: "139.7850",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Japanese", "Shojin Ryori"]),
    priceRange: "¥¥¥",
    features: JSON.stringify(["Traditional", "Course Menu", "Private Rooms"]),
    instagram: "@bon_fuscha",
    website: "https://www.fuscha-bon.com/",
    phone: "03-3872-0375",
    hours: "11:30-14:30, 17:00-20:00 (Reservation required)",
    description: "Traditional fuscha ryori (Buddhist vegetarian cuisine) restaurant established in 1959. All private tatami rooms.",
    descriptionJa: "1959年創業の伝統的な普茶料理（仏教精進料理）レストラン。全席個室の畳部屋。",
    heroImage: "/images/restaurants/bon.jpg",
  },
  {
    id: "nezu-no-ya",
    name: "Nezu no Ya",
    nameJa: "根津の谷",
    address: "3-37-3 Nezu, Bunkyo-ku, Tokyo",
    lat: "35.7200",
    lng: "139.7620",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Japanese", "Macrobiotic"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Macrobiotic", "Natural Foods", "Cafe"]),
    instagram: "@nezunoya",
    website: "https://nezunoya.jp/",
    phone: "03-5834-7292",
    hours: "11:30-18:00 (Closed Mon)",
    description: "Vegan restaurant and cafe in historic Nezu area. Macrobiotic menu with natural food store attached.",
    descriptionJa: "歴史的な根津エリアにあるヴィーガンレストラン＆カフェ。自然食品店併設のマクロビオティックメニュー。",
    heroImage: "/images/restaurants/nezu-no-ya.jpg",
  },
  {
    id: "minoya-asakusabashi",
    name: "Minoya",
    nameJa: "味農家",
    address: "1-9-8 Asakusabashi, Taito-ku, Tokyo",
    lat: "35.6970",
    lng: "139.7880",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Japanese", "Kaiseki"]),
    priceRange: "¥¥¥",
    features: JSON.stringify(["Seasonal", "Course Menu", "Counter Seating"]),
    instagram: "@minoya_asakusabashi",
    website: "https://minoya-asakusabashi.com/",
    phone: "03-5809-7484",
    hours: "18:00-22:00 (Reservation required, Closed Sun)",
    description: "Vegan kaiseki restaurant with monthly changing menu. Creative vegetable-focused course meals.",
    descriptionJa: "月替わりメニューのヴィーガン懐石レストラン。創造的な野菜中心のコース料理。",
    heroImage: "/images/restaurants/minoya.jpg",
  },
  {
    id: "saido-roppongi",
    name: "Saido",
    nameJa: "菜道",
    address: "7-4-4 Roppongi, Minato-ku, Tokyo",
    lat: "35.6627",
    lng: "139.7300",
    veganLevel: "Vegan Options",
    cuisineTypes: JSON.stringify(["Japanese", "Organic"]),
    priceRange: "¥¥¥",
    features: JSON.stringify(["Organic", "Farm-to-Table", "Elegant"]),
    instagram: "@saido_roppongi",
    website: "https://saido.tokyo/",
    phone: "03-5771-6777",
    hours: "11:30-14:30, 18:00-22:00 (Closed Mon)",
    description: "Upscale organic Japanese restaurant with vegan options. Farm-to-table concept with seasonal ingredients.",
    descriptionJa: "ヴィーガンオプションのある高級オーガニック和食レストラン。旬の食材を使ったファーム・トゥ・テーブルのコンセプト。",
    heroImage: "/images/restaurants/saido.jpg",
  },

  // Chinese Restaurants
  {
    id: "loving-hut-ikebukuro",
    name: "Loving Hut Ikebukuro",
    nameJa: "ラビングハット 池袋",
    address: "1-28-6 Minami-Ikebukuro, Toshima-ku, Tokyo",
    lat: "35.7295",
    lng: "139.7120",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Chinese", "Asian"]),
    priceRange: "¥",
    features: JSON.stringify(["International Chain", "Affordable", "Quick Service"]),
    instagram: "@lovinghut_japan",
    website: "https://lovinghut.jp/",
    phone: "03-5391-7481",
    hours: "11:00-21:00 (Daily)",
    description: "International vegan chain restaurant serving Asian-Chinese fusion cuisine. Affordable and casual.",
    descriptionJa: "アジア中華フュージョン料理を提供する国際的なヴィーガンチェーンレストラン。手頃な価格でカジュアル。",
    heroImage: "/images/restaurants/loving-hut.jpg",
  },
  {
    id: "vegetarian-beast",
    name: "Vegetarian Beast",
    nameJa: "ベジタリアンビースト",
    address: "2-7-13 Kitazawa, Setagaya-ku, Tokyo",
    lat: "35.6610",
    lng: "139.6680",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Chinese", "Taiwanese"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Taiwanese", "Spicy", "Casual"]),
    instagram: "@vegetarian_beast",
    website: "https://vegetarianbeast.com/",
    phone: "03-6407-0841",
    hours: "17:00-23:00 (Closed Tue)",
    description: "Vegan Taiwanese-Chinese restaurant in Shimokitazawa. Known for spicy mapo tofu and dan dan noodles.",
    descriptionJa: "下北沢にあるヴィーガン台湾中華レストラン。スパイシーな麻婆豆腐と担々麺が有名。",
    heroImage: "/images/restaurants/vegetarian-beast.jpg",
  },
  {
    id: "tenshin-akasaka",
    name: "Tenshin",
    nameJa: "天心",
    address: "3-10-4 Akasaka, Minato-ku, Tokyo",
    lat: "35.6750",
    lng: "139.7370",
    veganLevel: "Vegan Options",
    cuisineTypes: JSON.stringify(["Chinese", "Dim Sum"]),
    priceRange: "¥¥¥",
    features: JSON.stringify(["Dim Sum", "Elegant", "Course Menu"]),
    instagram: "@tenshin_akasaka",
    website: "https://tenshin-akasaka.com/",
    phone: "03-3584-0707",
    hours: "11:30-14:30, 17:30-22:00 (Daily)",
    description: "Upscale Chinese restaurant with vegan dim sum options. Elegant atmosphere perfect for special occasions.",
    descriptionJa: "ヴィーガン点心オプションのある高級中華レストラン。特別な機会にぴったりのエレガントな雰囲気。",
    heroImage: "/images/restaurants/tenshin.jpg",
  },

  // Italian & Western
  {
    id: "vegan-eat-tokyo",
    name: "Vegan Eat Tokyo",
    nameJa: "ヴィーガンイート東京",
    address: "2-14-8 Asakusa, Taito-ku, Tokyo",
    lat: "35.7148",
    lng: "139.7967",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Italian", "Western"]),
    priceRange: "¥¥¥",
    features: JSON.stringify(["Fine Dining", "Wine Pairing", "Romantic"]),
    instagram: "@veganeat_tokyo",
    website: "https://veganeat.tokyo/",
    phone: "03-6231-6204",
    hours: "17:30-22:00 (Closed Mon)",
    description: "Fine dining vegan Italian restaurant. Fusion of Japanese and Italian cuisine with wine pairing options.",
    descriptionJa: "ファインダイニングのヴィーガンイタリアンレストラン。和伊融合料理とワインペアリングオプション。",
    heroImage: "/images/restaurants/vegan-eat-tokyo.jpg",
  },
  {
    id: "ripple-ebisu",
    name: "Ripple",
    nameJa: "リップル",
    address: "1-22-3 Ebisu-Nishi, Shibuya-ku, Tokyo",
    lat: "35.6467",
    lng: "139.7083",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Italian", "Pizza"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Pizza", "Pasta", "Casual"]),
    instagram: "@ripple_ebisu",
    website: "https://ripple-ebisu.com/",
    phone: "03-6455-2985",
    hours: "11:30-15:00, 17:30-22:00 (Closed Wed)",
    description: "Vegan Italian restaurant specializing in pizza and pasta. Cozy atmosphere in Ebisu.",
    descriptionJa: "ピザとパスタ専門のヴィーガンイタリアンレストラン。恵比寿の居心地の良い雰囲気。",
    heroImage: "/images/restaurants/ripple.jpg",
  },
  {
    id: "2foods-ginza-loft",
    name: "2foods Ginza Loft",
    nameJa: "2foods 銀座ロフト",
    address: "4-6 Ginza 2-Chome, Chuo-ku, Tokyo (Ginza Loft 1F)",
    lat: "35.6740",
    lng: "139.7650",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Western", "Fast Food"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Juice Bar", "Takeout", "Gluten-Free"]),
    instagram: "@2foods_tokyo",
    website: "https://2foods.jp/",
    phone: "03-3562-5528",
    hours: "11:00-21:00 (Daily)",
    description: "Vegan fast food restaurant in Ginza Loft. Burgers, nuggets, and donuts all plant-based.",
    descriptionJa: "銀座ロフト内のヴィーガンファストフードレストラン。バーガー、ナゲット、ドーナツすべて植物ベース。",
    heroImage: "/images/restaurants/2foods.jpg",
  },

  // Thai & Asian
  {
    id: "thai-vegan-yoyogi",
    name: "Thai Vegan",
    nameJa: "タイヴィーガン",
    address: "1-30-1 Yoyogi, Shibuya-ku, Tokyo",
    lat: "35.6830",
    lng: "139.7020",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Thai", "Asian"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Authentic", "Spicy", "Lunch Sets"]),
    instagram: "@thaivegan_tokyo",
    website: "https://thaivegan.jp/",
    phone: "03-5302-8133",
    hours: "11:30-15:00, 17:30-22:00 (Closed Mon)",
    description: "Authentic vegan Thai restaurant near Yoyogi Station. Full menu of classic Thai dishes made plant-based.",
    descriptionJa: "代々木駅近くの本格ヴィーガンタイ料理店。クラシックなタイ料理を植物ベースで再現した豊富なメニュー。",
    heroImage: "/images/restaurants/thai-vegan.jpg",
  },
  {
    id: "paprika-shokudo",
    name: "Paprika Shokudo",
    nameJa: "パプリカ食堂",
    address: "3-26-13 Nishi-Ogikubo, Suginami-ku, Tokyo",
    lat: "35.7030",
    lng: "139.5970",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Thai", "Asian"]),
    priceRange: "¥",
    features: JSON.stringify(["Casual", "Affordable", "Lunch"]),
    instagram: "@paprika_shokudo",
    website: "https://paprika-shokudo.com/",
    phone: "03-5336-6345",
    hours: "11:30-20:00 (Closed Tue)",
    description: "Casual vegan Thai restaurant in Nishi-Ogikubo. Affordable lunch sets and friendly atmosphere.",
    descriptionJa: "西荻窪のカジュアルなヴィーガンタイ料理店。手頃なランチセットとフレンドリーな雰囲気。",
    heroImage: "/images/restaurants/paprika-shokudo.jpg",
  },
  {
    id: "komeda-is",
    name: "Komeda Is",
    nameJa: "コメダイズ",
    address: "1-14-11 Shibuya, Shibuya-ku, Tokyo",
    lat: "35.6595",
    lng: "139.7025",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Cafe", "Japanese"]),
    priceRange: "¥",
    features: JSON.stringify(["Chain", "Breakfast", "Coffee"]),
    instagram: "@komeda_is",
    website: "https://www.komeda-is.com/",
    phone: "03-6427-0505",
    hours: "7:00-21:00 (Daily)",
    description: "Vegan version of the popular Komeda coffee chain. Plant-based versions of classic menu items.",
    descriptionJa: "人気のコメダ珈琲チェーンのヴィーガン版。クラシックメニューの植物ベースバージョン。",
    heroImage: "/images/restaurants/komeda-is.jpg",
  },

  // Specialty & Others
  {
    id: "loca-kitchen-koenji",
    name: "Loca Kitchen",
    nameJa: "ロカキッチン",
    address: "3-56-2 Koenji-Kita, Suginami-ku, Tokyo",
    lat: "35.7060",
    lng: "139.6500",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["International", "Bar"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Late Night", "Wine", "Casual"]),
    instagram: "@loca_kitchen",
    website: "https://locakitchen.com/",
    phone: "03-5356-8558",
    hours: "18:00-24:00 (Closed Sun)",
    description: "Vegan bar and restaurant in Koenji. Open until midnight with organic wine selection.",
    descriptionJa: "高円寺のヴィーガンバー＆レストラン。深夜0時まで営業、オーガニックワインセレクション。",
    heroImage: "/images/restaurants/loca-kitchen.jpg",
  },
  {
    id: "dot-raw-roppongi",
    name: ".RAW",
    nameJa: "ドットロー",
    address: "7-21-19 Roppongi, Minato-ku, Tokyo",
    lat: "35.6640",
    lng: "139.7290",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Raw Food", "Cafe"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Raw Food", "Salad Bar", "Organic"]),
    instagram: "@dotraw_tokyo",
    website: "https://dotraw.jp/",
    phone: "03-6447-4753",
    hours: "11:00-20:00 (Closed Mon)",
    description: "Raw food cafe with salad bar featuring homegrown sprouts. Raw vegan desserts available.",
    descriptionJa: "自家栽培スプラウトのサラダバーがあるローフードカフェ。ローヴィーガンデザートあり。",
    heroImage: "/images/restaurants/dot-raw.jpg",
  },
  {
    id: "6889-cafe",
    name: "6889cafe",
    nameJa: "6889カフェ",
    address: "2-31-8 Jingumae, Shibuya-ku, Tokyo",
    lat: "35.6690",
    lng: "139.7080",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Cafe", "Dessert"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Desserts", "Coffee", "Instagrammable"]),
    instagram: "@6889cafe",
    website: "https://6889cafe.com/",
    phone: "03-6804-3773",
    hours: "11:00-19:00 (Closed Wed)",
    description: "Stylish vegan cafe in Harajuku. Famous for creative desserts and specialty coffee.",
    descriptionJa: "原宿のスタイリッシュなヴィーガンカフェ。創造的なデザートとスペシャルティコーヒーが有名。",
    heroImage: "/images/restaurants/6889cafe.jpg",
  },
  {
    id: "te-cor-gentil",
    name: "Te cor gentil",
    nameJa: "テコールジャンティ",
    address: "1-8-7 Azabujuban, Minato-ku, Tokyo",
    lat: "35.6560",
    lng: "139.7350",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["French", "Fine Dining"]),
    priceRange: "¥¥¥",
    features: JSON.stringify(["French", "Course Menu", "Elegant"]),
    instagram: "@tecorgentil",
    website: "https://tecorgentil.com/",
    phone: "03-6435-3988",
    hours: "12:00-15:00, 18:00-22:00 (Closed Mon)",
    description: "Vegan French fine dining restaurant in Azabujuban. Elegant course menus with seasonal ingredients.",
    descriptionJa: "麻布十番のヴィーガンフレンチファインダイニング。旬の食材を使ったエレガントなコースメニュー。",
    heroImage: "/images/restaurants/te-cor-gentil.jpg",
  },
  {
    id: "tudore-tranquility",
    name: "Tudore Tranquility",
    nameJa: "トゥドレトランキリティ",
    address: "1-5-8 Ebisu, Shibuya-ku, Tokyo",
    lat: "35.6467",
    lng: "139.7100",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Cafe", "Organic"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Organic", "Gluten-Free", "Wellness"]),
    instagram: "@tudore_tranquility",
    website: "https://tudore.com/",
    phone: "03-6455-4567",
    hours: "10:00-20:00 (Daily)",
    description: "Organic vegan cafe focused on wellness. Gluten-free options and superfood bowls available.",
    descriptionJa: "ウェルネスに焦点を当てたオーガニックヴィーガンカフェ。グルテンフリーオプションとスーパーフードボウルあり。",
    heroImage: "/images/restaurants/tudore.jpg",
  },
  {
    id: "falafel-brothers",
    name: "Falafel Brothers",
    nameJa: "ファラフェルブラザーズ",
    address: "1-19-3 Jinnan, Shibuya-ku, Tokyo",
    lat: "35.6620",
    lng: "139.6975",
    veganLevel: "Vegan Options",
    cuisineTypes: JSON.stringify(["Middle Eastern", "Fast Food"]),
    priceRange: "¥",
    features: JSON.stringify(["Falafel", "Takeout", "Quick"]),
    instagram: "@falafelbrothers",
    website: "https://falafelbrothers.jp/",
    phone: "03-6455-0789",
    hours: "11:00-21:00 (Daily)",
    description: "Fast casual Middle Eastern restaurant with vegan falafel wraps and plates. Quick and affordable.",
    descriptionJa: "ヴィーガンファラフェルラップとプレートを提供するファストカジュアル中東料理店。早くて手頃。",
    heroImage: "/images/restaurants/falafel-brothers.jpg",
  },
  {
    id: "brown-sugar-1st",
    name: "Brown Sugar 1st",
    nameJa: "ブラウンシュガーファースト",
    address: "5-3-1 Minami-Aoyama, Minato-ku, Tokyo",
    lat: "35.6640",
    lng: "139.7130",
    veganLevel: "Vegan Options",
    cuisineTypes: JSON.stringify(["Cafe", "Organic"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Organic", "Pancakes", "Healthy"]),
    instagram: "@brownsugar1st",
    website: "https://www.brownsugar1st.com/",
    phone: "03-5778-4635",
    hours: "9:00-18:00 (Daily)",
    description: "Organic cafe with vegan pancake options. Focus on natural sweeteners and healthy ingredients.",
    descriptionJa: "ヴィーガンパンケーキオプションのあるオーガニックカフェ。天然甘味料と健康的な食材に焦点。",
    heroImage: "/images/restaurants/brown-sugar.jpg",
  },
  {
    id: "vege-charger-akasaka",
    name: "VEGE CHARGER Akasaka",
    nameJa: "ベジチャージャー 赤坂",
    address: "3-11-14 Akasaka, Minato-ku, Tokyo",
    lat: "35.6755",
    lng: "139.7365",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Juice Bar", "Cafe"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Smoothies", "Salads", "Healthy"]),
    instagram: "@vegecharger",
    website: "https://vegecharger.com/",
    phone: "03-6230-2345",
    hours: "8:00-20:00 (Mon-Fri), 10:00-18:00 (Sat-Sun)",
    description: "Vegan juice bar and cafe in Akasaka. Fresh smoothies, salads, and healthy bowls.",
    descriptionJa: "赤坂のヴィーガンジュースバー＆カフェ。フレッシュスムージー、サラダ、ヘルシーボウル。",
    heroImage: "/images/restaurants/vege-charger.jpg",
  },
  {
    id: "tsumugu-cafe",
    name: "TSUMUGU CAFE",
    nameJa: "ツムグカフェ",
    address: "4-14-3 Kanamecho, Toshima-ku, Tokyo",
    lat: "35.7350",
    lng: "139.7020",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Cafe", "Taiwanese"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Taiwanese Tea", "Vegan Food", "Cozy"]),
    instagram: "@tsumugu_cafe",
    website: "https://tsumugucafe.com/",
    phone: "03-5985-4321",
    hours: "11:00-19:00 (Closed Tue)",
    description: "Vegan cafe specializing in Taiwanese tea and plant-based food. Cozy atmosphere in Ikebukuro area.",
    descriptionJa: "台湾茶と植物ベースフードを専門とするヴィーガンカフェ。池袋エリアの居心地の良い雰囲気。",
    heroImage: "/images/restaurants/tsumugu-cafe.jpg",
  },
  {
    id: "soy-love-ebisu",
    name: "SOY LOVE",
    nameJa: "ソイラブ",
    address: "1-11-2 Ebisu, Shibuya-ku, Tokyo",
    lat: "35.6465",
    lng: "139.7095",
    veganLevel: "100% Vegan",
    cuisineTypes: JSON.stringify(["Japanese", "Tofu"]),
    priceRange: "¥¥",
    features: JSON.stringify(["Tofu Dishes", "Soy Meat", "Healthy"]),
    instagram: "@soylove_ebisu",
    website: "https://soylove.jp/",
    phone: "03-5795-0123",
    hours: "11:30-15:00, 17:30-22:00 (Closed Mon)",
    description: "Vegan restaurant specializing in tofu and soy meat dishes. Creative takes on Japanese classics.",
    descriptionJa: "豆腐と大豆ミート料理専門のヴィーガンレストラン。日本の定番料理を創造的にアレンジ。",
    heroImage: "/images/restaurants/soy-love.jpg",
  },
];

